//#define DEBUG

using Elements.Core;
using FrooxEngine;
using FrooxEngine.UIX;
using HarmonyLib;
using ResoniteModLoader;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using static InspectorDelegateCaller.Helper;
using Caching;

#if DEBUG
using ResoniteHotReloadLib;
#endif

namespace InspectorDelegateCaller
{
	public class InspectorDelegateCaller : ResoniteMod
	{
		public override string Name => "InspectorDelegateCaller";
		public override string Author => "eia485 / Nytra";
		public override string Version => "1.5.1";
		public override string Link => "https://github.com/Nytra/ResoniteInspectorDelegateCaller";

		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_Enabled = new("enabled", "should the mod be enabled", () => true);

		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_Action = new("actions", "show callable actions in inspectors", () => true);
		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_ArgAction = new("argActions", "show any action with arguments in inspectors", () => true);
		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_Buttons = new("buttons", "show callable buttons in inspectors", () => true);
		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_ArgButtons = new("argButtons", "show any button with arguments in inspectors", () => true);

		// hide the slot destroy buttons because they are easy to accidentally click and they are not undoable
		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_ShowSlotDestroy = new("showSlotDestroy", "show the slot destroy buttons in inspectors", () => false);

		// skip generating buttons if they were already generated by some other method
		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_SkipDuplicates = new("skipDuplicates", "skip duplicates", () => true);
		//[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_SkipIndirectDuplicates = new("skipIndirectDuplicates", "if skip duplicates is true, skip methods passed as arguments to other methods (may not always be appropriate)", () => false, internalAccessOnly: true);

		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_ShowNonPublic = new("showNonPublic", "show buttons for non-public methods", () => false);

		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_ExtraDebug = new("extraDebug", "extra debug logging", () => false);

		static ModConfiguration config;

		static MethodInfo destroySlotMethod = AccessTools.Method(typeof(Slot), nameof(Slot.Destroy), []);
		static MethodInfo destroySlotPreservingAssetsMethod = AccessTools.Method(typeof(Slot), nameof(Slot.DestroyPreservingAssets), []);

		static Harmony harmony;

		public override void OnEngineInit()
		{
			config = GetConfiguration();
#if DEBUG
			HotReloader.RegisterForHotReload(this);
#endif
			PatchStuff();
		}

#if DEBUG
		static void BeforeHotReload()
		{
			harmony.UnpatchAll(harmony.Id);
			config.OnThisConfigurationChanged -= OnConfigChange;
			FreeMemory();
		}

		static void OnHotReload(ResoniteMod modInstance)
		{
			config = modInstance.GetConfiguration();
			PatchStuff();
		}
#endif

		static void ExtraDebug(Func<string> messageProducer)
		{
			if (config.GetValue(Key_ExtraDebug))
			{
				DebugFunc(messageProducer);
			}
		}

		static void ExtraDebug(string msg)
		{
			if (config.GetValue(Key_ExtraDebug))
			{
				Debug(msg);
			}
		}

		static void PatchStuff()
		{
#if DEBUG
			UniLog.FlushEveryMessage = true;
#endif
			harmony = new Harmony("owo.Nytra.InspectorDelegateCaller");
			harmony.PatchAll();
			config.OnThisConfigurationChanged += OnConfigChange;

#if DEBUG
			TemporaryObjectStore.DebugLoggingCallback = (string msg) =>
			{
				Debug(msg);
			};
#endif
			//DebugPrintAllSyncMethods();
		}

		static void OnConfigChange(ConfigurationChangedEvent configurationChangedEvent)
		{
			var key = configurationChangedEvent.Key;
			if (key == Key_ShowNonPublic || key == Key_ShowSlotDestroy)
			{
				FreeMemory();
			}
		}

		static void FreeMemory()
		{
			CacheManager.ClearAllCaches();
		}

		static bool IsButtonAlreadyGenerated(Worker worker, ParameterInfo[] param, UIBuilder ui, Slot workerUiRootSlot, ComponentDataCache compData, MethodDataCache methodData)
		{
			// assumed to be ButtonEventHandler
			if (param.Length == 2 && compData.buttonsInChildren.Any((Button btn) => btn.Pressed.Target != null && btn.Pressed.Target.Method.MethodHandle == methodData.method.MethodHandle))
			{
				ExtraDebug(() => $"Button found for method {methodData.method.Name} on worker {worker.Name}");
				return true;
			}

			// assumed to be ButtonEventHandler or ButtonEventHandler<T>
			if ((param.Length == 3 || param.Length == 2) && compData.buttonRelayBasesInChildren.Any((ButtonRelayBase btnRelay) => btnRelay.GetSyncMember("ButtonPressed") is ISyncDelegate syncDelegate && syncDelegate.Method != null && syncDelegate.Method.Method.MethodHandle == methodData.method.MethodHandle))
			{
				ExtraDebug(() => $"ButtonRelay found for method {methodData.method.Name} on worker {worker.Name}");
				return true;
			}

			// == Case study: AudioZitaReverb ==
			// this component will generate what looks like duplicate buttons but they are actually not the same
			//
			// half of the generated buttons are ButtonRelays which call SetPreset(btn, data, Action) ... note that it passes an Action as argument
			// the other half of generated buttons are those Actions
			//
			// It is possible to detect and skip these but you might not always want to because they are technically different methods

			//if (config.GetValue(Key_SkipIndirectDuplicates) && param.Length == 0 && compData.buttonRelayBasesInChildren.Any((ButtonRelayBase btnRelay) => btnRelay.GetSyncMember("Argument") is ISyncDelegate syncDelegate && syncDelegate.Method != null && syncDelegate.Method.Method.MethodHandle == m.MethodHandle))
			//{
			//	ExtraDebug($"ButtonRelay found with Argument for method {m.Name} on worker {worker.Name} (Indirect duplicate)");
			//	return true;
			//}

			return false;
		}

		internal static HashSet<MethodDataCache> GetAllValidSyncMethods(Type workerType)
		{
			var data = Cache<Type, HashSet<MethodDataCache>>.Get(workerType, type => 
			{
				var set = Pool.BorrowHashSet<MethodDataCache>();

				ExtraDebug(() => $"Worker: {workerType.Name}");

				GetAllMethods(workerType, set, CanMakeButtonForMethod);

				return set;
			}, onReleaseCallback: data =>
			{
				var toReturn = data.releasedObject as HashSet<MethodDataCache>;
				Pool.Return(ref toReturn);
			});
			return data;
		}

		class ComponentDataCache
		{
			public List<Button> buttonsInChildren;
			public List<ButtonRelayBase> buttonRelayBasesInChildren;
			public bool CanSkipDuplicates => buttonsInChildren != null && buttonRelayBasesInChildren != null;
		}

		static MethodDataCache CanMakeButtonForMethod(MethodInfo m)
		{
			if (m == null) return null;

			if (!HasSyncMethod(m)) return null;

			if (!config.GetValue(Key_ShowNonPublic) && !m.IsPublic) return null; // ToDo: only show public ones?

			// check for the slot destroy methods
			if (!config.GetValue(Key_ShowSlotDestroy) && (m == destroySlotMethod || m == destroySlotPreservingAssetsMethod)) return null;

			var param = m.GetParameters();
			bool isButtonEventHandler = false;

			if (param.Length > 3) // No button component supports these
			{
				return null;
			}
			else if (param.Length == 2 || param.Length == 3)
			{
				/// Could be <see cref="ButtonEventHandler"/> or <see cref="ButtonEventHandler{T}"/>, anything else we can't make a button for
				isButtonEventHandler = IsButtonEventHandler(param);
				if (!isButtonEventHandler)
				{
					return null;
				}
				else
				{
					if (param.Length == 2 && !config.GetValue(Key_Buttons)) return null;
					if (param.Length == 3 && !config.GetValue(Key_ArgButtons)) return null;
				}
			}
			else
			{
				if (m.ReturnType == typeof(void)) 
				{
					/// <see cref="Action"/> or <see cref="Action{T}"/>
					if (!config.GetValue(Key_Action) && !config.GetValue(Key_ArgAction))
					{
						return null;
					}
				}
				else
				{
					/// <see cref="Func{TResult}"/> or <see cref="Func{T, TResult}"/>
					/// No button component supports these
					return null;
				}
			}

			var data = new MethodDataCache();
			data.method = m;
			data.parameters = param;

			ExtraDebug(() => $"\t\t{m.ReturnType.GetNiceName()} {m.Name}({GetParamString(param)})");

			return data;
		}

		[HarmonyPatch(typeof(WorkerInspector), "BuildInspectorUI")]
		class InspectorDelegateCallerPatch
		{
			static void Postfix(Worker worker, UIBuilder ui)
			{
				if (!config.GetValue(Key_Enabled)) return;

				Type workerType = worker.GetType();

				Slot workerUiRoot = ui.CurrentRect?.Slot?.Parent;

				if (workerUiRoot == null)
				{
					Error($"workerUiRoot is null for worker {worker.Name} ({workerType.Name})!");
					return;
				}

				//Debug($"currentRect Slot parent hierarchy:\n{ui.CurrentRect.Slot.ParentHierarchyToString()}");

				// run this later so that the worker ui can finish generating fully, then it becomes possible to check for duplicate buttons
				worker.World.RunSynchronously(() =>
				{
					if (workerUiRoot.FilterWorldElement() is null || worker.FilterWorldElement() is null) return;

					var validMethods = GetAllValidSyncMethods(workerType);

					var compData = new ComponentDataCache();

					if (validMethods.Count > 0)
					{
						// Don't hide buttons on member editors or ref editors
						if (config.GetValue(Key_SkipDuplicates) && worker is not MemberEditor && worker is not RefEditor)
						{
							compData.buttonsInChildren = workerUiRoot.GetComponentsInChildren<Button>();
							compData.buttonRelayBasesInChildren = workerUiRoot.GetComponentsInChildren<ButtonRelayBase>();
						}
					}
					else
					{
						return;
					}

					RectTransform origRect = ui.CurrentRect;
					ui.NestInto(workerUiRoot);
					var origHeight = ui.Style.MinHeight;
					ui.Style.MinHeight = 24f;
					int count = 0;

					foreach (var methodData in validMethods)
					{
						try
						{
							var param = methodData.parameters;

							if (config.GetValue(Key_SkipDuplicates) && compData.CanSkipDuplicates && IsButtonAlreadyGenerated(worker, param, ui, workerUiRoot, compData, methodData)) continue;

							switch (param.Length)
							{
								case 0: // Action
									var b = ui.Button(methodData.method.Name);
									b.Slot.AttachComponent<ButtonActionTrigger>().OnPressed.Target = GetDelegate<Action>(methodData.method, worker);
									count++;
									break;
								case 1: // Action<T>
									var p0 = param[0];
									var pt0 = p0.ParameterType;
									if (ClassifyType(pt0, out bool isPrimitive, out bool isWorldElement, out bool isDelegate) && !isDelegate)
									{
										actionCallbackwitharg(isWorldElement, worker, ui, methodData.method, p0, pt0);
										count++;
									}
									break;
								case 2: // ButtonEventHandler
									ui.Button(methodData.method.Name).Pressed.Target = GetDelegate<ButtonEventHandler>(methodData.method, worker);
									count++;
									break;
								case 3: // ButtonEventHandler<T>
									var p2 = param[2];
									var pt2 = p2.ParameterType;
									if (ClassifyType(pt2, out bool isPrimitive2, out bool isWorldElement2, out bool isDelegate2))
									{
										Type compType = null;
										if (isWorldElement2)
											compType = typeof(ButtonRefRelay<>);
										else if (isDelegate2)
											compType = typeof(ButtonDelegateRelay<>);
										else
											compType = typeof(ButtonRelay<>);
										buttonCallbackwitharg(compType, worker, ui, methodData.method, p2, pt2);
										count++;
									}
									break;
							}
						}
						catch (Exception e)
						{
							Error($"Error when generating button for method {methodData.method.Name} on worker {worker.Name} ({workerType.Name}).\n{e}");
							ui.Text($"<color=red>Error, check log: {workerType.Name}.{methodData.method.Name}");
						}
					}

					ui.Style.MinHeight = origHeight;
					if (count > 0)
					{
						ui.Panel();
						ui.NestOut();
					}
					if (origRect != null) ui.NestInto(origRect);
				});
			}
		}

		private static T GetDelegate<T>(MethodInfo m, Worker w) where T : Delegate
		{
			return m.IsStatic ? Cache<MethodInfo, T>.Get(m, info => (T)info.CreateDelegate(typeof(T), null))
						      : (T)m.CreateDelegate(typeof(T), w);
		}

		private class ActionCallbackWithArgData
		{
			public Type apt;
			public Type t;
			public Type rt;
			public PropertyInfo targetProp;
			public FieldInfo callbackField;
			public string cbrvn;
			public FieldInfo cbrvnField;
			public Delegate staticDelegate;
			public MethodInfo callMethod;
			public ActionCallbackWithArgData(MethodInfo m, Type pt, bool isRef)
			{
				apt = typeof(Action<>).MakeGenericType(pt);
				t = (isRef ? typeof(CallbackRefArgument<>) : typeof(CallbackValueArgument<>)).MakeGenericType(pt);
				rt = typeof(SyncDelegate<>).MakeGenericType(apt);
				targetProp = rt.GetProperty("Target");
				callbackField = t.GetField("Callback");
				cbrvn = isRef ? "Reference" : "Value";
				cbrvnField = t.GetField(cbrvn);
				staticDelegate = m.CreateDelegate(apt, null);
				callMethod = t.GetMethod("Call");
			}
		}

		static void actionCallbackwitharg(bool isRef, Worker worker, UIBuilder ui, MethodInfo m, ParameterInfo p, Type pt)
		{
			ActionCallbackWithArgData data = Cache<MethodInfo, ActionCallbackWithArgData>.Get(m, info => new ActionCallbackWithArgData(info, pt, isRef));

			ui.HorizontalLayout();
			LocaleString str = m.Name;
			var b = ui.Button(in str);
			var apt = data.apt;
			Type t = data.t;
			var c = b.Slot.AttachComponent(t);
			Type rt = data.rt;
			data.targetProp.SetValue(data.callbackField.GetValue(c), m.IsStatic ? data.staticDelegate : m.CreateDelegate(apt, worker));
			SyncMemberEditorBuilder.Build(c.GetSyncMember(data.cbrvn), p.Name, data.cbrvnField, ui);
			b.Slot.AttachComponent<ButtonActionTrigger>().OnPressed.Target = (Action)data.callMethod.CreateDelegate(typeof(Action), c);
			ui.NestOut();
		}

		private class ButtonCallbackWithArgData
		{
			public Type bpt;
			public Type t;
			public Type rt;
			public PropertyInfo targetProp;
			public FieldInfo buttonPressedField;
			public FieldInfo argumentField;
			public Delegate staticDelegate;
			public ButtonCallbackWithArgData(Type genType, MethodInfo m, Type pt)
			{
				bpt = typeof(ButtonEventHandler<>).MakeGenericType(pt);
				t = genType.MakeGenericType(pt);
				rt = typeof(SyncDelegate<>).MakeGenericType(bpt);
				targetProp = rt.GetProperty("Target");
				buttonPressedField = t.GetField("ButtonPressed");
				argumentField = t.GetField("Argument");
				staticDelegate = m.CreateDelegate(bpt, null);
			}
		}

		static void buttonCallbackwitharg(Type genType, Worker worker, UIBuilder ui, MethodInfo m, ParameterInfo p, Type pt)
		{
			ButtonCallbackWithArgData data = Cache<MethodInfo, ButtonCallbackWithArgData>.Get(m, info => new ButtonCallbackWithArgData(genType, info, pt));

			ui.HorizontalLayout();
			LocaleString str = m.Name;
			var b = ui.Button(in str);
			var bpt = data.bpt;
			Type t = data.t;
			var c = b.Slot.AttachComponent(t);
			Type rt = data.rt;
			data.targetProp.SetValue(data.buttonPressedField.GetValue(c), m.IsStatic ? data.staticDelegate : m.CreateDelegate(bpt, worker));
			SyncMemberEditorBuilder.Build(c.GetSyncMember("Argument"), p.Name, data.argumentField, ui);
			ui.NestOut();
		}
	}
}