#define DEBUG

using Elements.Core;
using FrooxEngine;
using FrooxEngine.UIX;
using HarmonyLib;
using ResoniteModLoader;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Data;
using System.Threading.Tasks;
using FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.FrooxEngine.Elements;
using System.Security.Cryptography;
using FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Math.Constants;
using System.ComponentModel;
using static InspectorDelegateCaller.Helper;




#if DEBUG
using ResoniteHotReloadLib;
#endif

namespace InspectorDelegateCaller
{
	public class InspectorDelegateCaller : ResoniteMod
	{
		public override string Name => "InspectorDelegateCaller";
		public override string Author => "eia485 / Nytra";
		public override string Version => "1.5.0";
		public override string Link => "https://github.com/Nytra/ResoniteInspectorDelegateCaller";

		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_Enabled = new("enabled", "should the mod be enabled", () => true);

		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_Action = new("actions", "show callable actions in inspectors", () => true);
		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_ArgAction = new("argActions", "show any action with arguments in inspectors", () => true);
		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_Buttons = new("buttons", "show callable buttons in inspectors", () => false);
		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_ArgButtons = new("argButtons", "show any button with arguments in inspectors", () => true);

		// hide the slot destroy buttons because they are easy to accidentally click and they are not undoable
		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_ShowSlotDestroy = new("showSlotDestroy", "show the slot destroy buttons in inspectors", () => false);

		// skip generating buttons if they were already generated by some other method
		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_SkipDuplicates = new("skipDuplicates", "skip duplicates", () => true);
		//[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_SkipIndirectDuplicates = new("skipIndirectDuplicates", "if skip duplicates is true, skip methods passed as arguments to other methods (may not always be appropriate)", () => false, internalAccessOnly: true);

		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_ShowNonPublic = new("showNonPublic", "show buttons for non-public methods", () => false);

		[AutoRegisterConfigKey] static ModConfigurationKey<bool> Key_ExtraDebug = new("extraDebug", "extra debug logging", () => false);

		static ModConfiguration config;

		static MethodInfo destroySlotMethod = AccessTools.Method(typeof(Slot), nameof(Slot.Destroy), []);
		static MethodInfo destroySlotPreservingAssetsMethod = AccessTools.Method(typeof(Slot), nameof(Slot.DestroyPreservingAssets), []);

		static Dictionary<Type, TemporaryObjectStore> methodInfoStore = new();

		static Harmony harmony;

		public override void OnEngineInit()
		{
			config = GetConfiguration();
#if DEBUG
			HotReloader.RegisterForHotReload(this);
#endif
			PatchStuff();
		}

#if DEBUG
		static void BeforeHotReload()
		{
			methodInfoStore.Clear();
			harmony.UnpatchAll(harmony.Id);
			config.OnThisConfigurationChanged -= OnConfigChange;
		}

		static void OnHotReload(ResoniteMod modInstance)
		{
			config = modInstance.GetConfiguration();
			PatchStuff();
		}
#endif

		static void ExtraDebug(Func<string> messageProducer)
		{
			if (config.GetValue(Key_ExtraDebug))
			{
				DebugFunc(messageProducer);
			}
		}

		static void ExtraDebug(string msg)
		{
			if (config.GetValue(Key_ExtraDebug))
			{
				Debug(msg);
			}
		}

		static void PatchStuff()
		{
			harmony = new Harmony("owo.Nytra.InspectorDelegateCaller");
			harmony.PatchAll();
			config.OnThisConfigurationChanged += OnConfigChange;

//#if DEBUG
//			TemporaryObjectStore.DebugLoggingCallback = (string msg) => 
//			{
//				Debug(msg);
//			};
//#endif
		}

		static void OnConfigChange(ConfigurationChangedEvent configurationChangedEvent)
		{
			var key = configurationChangedEvent.Key;
			if (key == Key_ShowNonPublic || key == Key_ShowSlotDestroy)
			{
				foreach (var objectStore in methodInfoStore.Values)
				{
					if (objectStore.HasStoredObject)
						objectStore.RequestRelease();
				}
				methodInfoStore.Clear();
			}
		}

		static bool IsButtonAlreadyGenerated(Worker worker, ParameterInfo[] param, UIBuilder ui, Slot workerUiRootSlot, ComponentDataCache compData, MethodDataCache methodData)
		{
			if (methodData.isFunc) return false; // can these be generated?

			if (param.Length == 2 && methodData.isButtonEventHandler && compData.buttonsInChildren.Any((Button btn) => btn.Pressed.Target != null && btn.Pressed.Target.Method.MethodHandle == methodData.method.MethodHandle))
			{
				ExtraDebug($"Button found for method {methodData.method.Name} on worker {worker.Name}");
				return true;
			}

			if ((param.Length == 3 || param.Length == 2) && methodData.isButtonEventHandler && compData.buttonRelayBasesInChildren.Any((ButtonRelayBase btnRelay) => btnRelay.GetSyncMember("ButtonPressed") is ISyncDelegate syncDelegate && syncDelegate.Method != null && syncDelegate.Method.Method.MethodHandle == methodData.method.MethodHandle))
			{
				ExtraDebug($"ButtonRelay found for method {methodData.method.Name} on worker {worker.Name}");
				return true;
			}

			// == Case study: AudioZitaReverb ==
			// this component will generate what looks like duplicate buttons but they are actually not the same
			//
			// half of the generated buttons are ButtonRelays which call SetPreset(btn, data, Action) ... note that it passes an Action as argument
			// the other half of generated buttons are those Actions
			//
			// It is possible to detect and skip these but you might not always want to because they are technically different methods

			//if (config.GetValue(Key_SkipIndirectDuplicates) && param.Length == 0 && compData.buttonRelayBasesInChildren.Any((ButtonRelayBase btnRelay) => btnRelay.GetSyncMember("Argument") is ISyncDelegate syncDelegate && syncDelegate.Method != null && syncDelegate.Method.Method.MethodHandle == m.MethodHandle))
			//{
			//	ExtraDebug($"ButtonRelay found with Argument for method {m.Name} on worker {worker.Name} (Indirect duplicate)");
			//	return true;
			//}

			return false;
		}

		public static HashSet<MethodDataCache> GetAllValidSyncMethods(Type t)
		{
			TemporaryObjectStore objStore;
			if (methodInfoStore.TryGetValue(t, out objStore))
			{
				var rememberedObj = objStore.Access();
				if (rememberedObj != null)
					return rememberedObj as HashSet<MethodDataCache>;
			}
			else
			{
				objStore = new TemporaryObjectStore();
				methodInfoStore[t] = objStore;
			}

			var set = Pool.BorrowHashSet<MethodDataCache>();

			GetAllMethods(t, set, MethodCheck);

			objStore.StoreTemporarily(set, _suppressExceptions: true, _onReleaseCallback: (data) => 
			{ 
				//var returnedSet = data.releasedObject as HashSet<MethodDataCache>;
				Pool.Return(ref set);
			});

			return set;
		}

		class ComponentDataCache
		{
			public List<Button> buttonsInChildren;
			public List<ButtonRelayBase> buttonRelayBasesInChildren;
			public bool IsOkayToSkipDuplicates => buttonsInChildren != null && buttonRelayBasesInChildren != null;
		}

		public class MethodDataCache
		{
			public bool isButtonEventHandler;
			public bool isFunc;
			public bool isFuncSupported;
			public MethodInfo method;
			public ParameterInfo[] param;
		}

		static MethodDataCache MethodCheck(MethodInfo m)
		{
			if (m == null) return null;

			if (!HasSyncMethod(m)) return null;

			if (!config.GetValue(Key_ShowNonPublic) && !m.IsPublic) return null; // ToDo: only show public ones?

			// check for the slot destroy methods
			if (!config.GetValue(Key_ShowSlotDestroy) && (m == destroySlotMethod || m == destroySlotPreservingAssetsMethod)) return null;

			var param = m.GetParameters();

			// Too many params 
			if (param.Length > 3)
				return null;

			bool isButtonEventHandler = false;
			bool isFunc = false;
			bool isFuncSupported = false;

			// Can only make a button for these if it's a ButtonEventHandler or ButtonEventHandler<T> (i.e. has params (IButton, ButtonEventData) or (IButton, ButtonEventData, T))
			if (param.Length >= 2)
			{
				isButtonEventHandler = IsButtonEventHandler(param);
				if (!isButtonEventHandler) return null;
			}
			else if (m.ReturnType == typeof(void)) // means it's an Action
			{
				if (!config.GetValue(Key_Action) && !config.GetValue(Key_ArgAction)) return null;
			}
			else // it's a Func
			{
				isFunc = true;
				if (!ParamsAreDataModelTypes(param) || !m.ReturnType.IsDataModelType())
				{
					//return null;
				}
				else
				{
					isFuncSupported = true;
				}
			}

			string funcText = "";
			if (isFunc && !isFuncSupported)
				funcText = "⚠️ ";

			ExtraDebug($"\t\t{funcText}{m.ReturnType.GetNiceName()} {m.Name}({GetParamString(param)})");

			var data = new MethodDataCache();
			data.isButtonEventHandler = isButtonEventHandler;
			data.isFunc = isFunc;
			data.isFuncSupported = isFuncSupported;
			data.method = m;
			data.param = param;

			return data;
		}

		[HarmonyPatch(typeof(WorkerInspector), "BuildInspectorUI")]
		class InspectorDelegateCallerPatch
		{
			static void Postfix(Worker worker, UIBuilder ui)
			{
				if (!config.GetValue(Key_Enabled)) return;

				Type workerType = worker.GetType();

				Slot workerUiRoot = ui.CurrentRect?.Slot?.Parent;

				if (workerUiRoot == null)
				{
					// if the workerUiRoot is null then something is wrong
					Error($"workerUiRoot is null for worker {worker.Name} ({workerType.Name})!");
					return;
				}

				//Debug($"currentRect Slot parent hierarchy:\n{ui.CurrentRect.Slot.ParentHierarchyToString()}");

				// run this later so that the worker ui can finish generating fully, then it becomes possible to check for duplicate buttons
				worker.World.RunSynchronously(() =>
				{
					ExtraDebug(() => $"Worker: {worker.Name} ({workerType.Name})");

					var validMethods = GetAllValidSyncMethods(workerType);

					var compData = new ComponentDataCache();

					if (validMethods.Count > 0)
					{
						// Don't hide buttons on member editors or ref editors
						if (config.GetValue(Key_SkipDuplicates) && worker is not MemberEditor && worker is not RefEditor)
						{
							compData.buttonsInChildren = workerUiRoot.GetComponentsInChildren<Button>();
							compData.buttonRelayBasesInChildren = workerUiRoot.GetComponentsInChildren<ButtonRelayBase>();
						}
					}
					else
					{
						return;
					}

					RectTransform origRect = ui.CurrentRect;
					ui.NestInto(workerUiRoot);
					var origHeight = ui.Style.MinHeight;
					ui.Style.MinHeight = 24f;
					int count = 0;

					foreach (var methodData in validMethods)
					{
						try
						{
							var param = methodData.param;

							if (config.GetValue(Key_SkipDuplicates) && compData.IsOkayToSkipDuplicates && IsButtonAlreadyGenerated(worker, param, ui, workerUiRoot, compData, methodData)) continue;

							switch (param.Length)
							{
								case 0: //could have some branching mess here. may be marginally faster
									if (methodData.isFunc)
									{
										funcWithoutArgs(worker, ui, methodData);
										count++;
									}
									else if (config.GetValue(Key_Action))
									{
										LocaleString str = methodData.method.Name;

										var b = ui.Button(in str);
										b.Slot.AttachComponent<ButtonActionTrigger>().OnPressed.Target = (Action)methodData.method.CreateDelegate(typeof(Action), methodData.method.IsStatic ? null : worker);
										count++;
									}
									break;
								case 1:
									if (methodData.isFunc)
									{
										funcWithArgs(worker, ui, param, methodData);
										count++;
									}
									else if (config.GetValue(Key_ArgAction))
									{
										var p = param[0];
										var pt = p.ParameterType;
										if (ClassifyType(pt, out bool isPrimitive, out bool isWorldElement, out bool isDelegate) && !isDelegate)
										{
											actionCallbackwitharg(isWorldElement, worker, ui, methodData.method, p, pt);
											count++;
										}
									}
									break;
								case 2:
									if (config.GetValue(Key_Buttons) && methodData.isButtonEventHandler)
									{
										LocaleString str = methodData.method.Name;
										var b = ui.Button(in str).Pressed.Target = (ButtonEventHandler)methodData.method.CreateDelegate(typeof(ButtonEventHandler), methodData.method.IsStatic ? null : worker);
										count++;
									}
									break;
								case 3:
									if (config.GetValue(Key_ArgButtons) && methodData.isButtonEventHandler)
									{
										var p = param[2];
										var pt = p.ParameterType;
										if (ClassifyType(pt, out bool isPrimitive, out bool isWorldElement, out bool isDelegate))
										{
											Type compType = null;
											if (isWorldElement)
												compType = typeof(ButtonRefRelay<>);
											else if (isDelegate)
												compType = typeof(ButtonDelegateRelay<>);
											else
												compType = typeof(ButtonRelay<>);
											buttonCallbackwitharg(compType, worker, ui, methodData.method, p, pt);
											count++;
										}
									}
									break;
							}
						}
						catch (Exception e)
						{
							Error($"Error when generating button for method {methodData.method.Name} on worker {worker.Name} ({workerType.Name}).\n{e}");
							ui.Text($"<color=red>Error, check log: {workerType.Name}.{methodData.method.Name}");
						}
					}

					ui.Style.MinHeight = origHeight;
					if (count > 0)
					{
						ui.Panel();
						ui.NestOut();
					}
					if (origRect != null) ui.NestInto(origRect);
				});
			}
		}

		static void actionCallbackwitharg(bool isRef, Worker worker, UIBuilder ui, MethodInfo m, ParameterInfo p, Type pt)
		{
			ui.HorizontalLayout();
			LocaleString str = m.Name;
			var b = ui.Button(in str);
			var apt = typeof(Action<>).MakeGenericType(pt);
			Type t = (isRef ? typeof(CallbackRefArgument<>) : typeof(CallbackValueArgument<>)).MakeGenericType(pt);
			var c = b.Slot.AttachComponent(t);
			Type rt = typeof(SyncDelegate<>).MakeGenericType(apt);
			rt.GetProperty("Target").SetValue(t.GetField("Callback").GetValue(c), m.CreateDelegate(apt, m.IsStatic ? null : worker));
			var cbrvn = isRef ? "Reference" : "Value";
			SyncMemberEditorBuilder.Build(c.GetSyncMember(cbrvn), p.Name, t.GetField(cbrvn), ui);
			b.Slot.AttachComponent<ButtonActionTrigger>().OnPressed.Target = (Action)t.GetMethod("Call").CreateDelegate(typeof(Action), c);
			ui.NestOut();
		}

		static void buttonCallbackwitharg(Type genType, Worker worker, UIBuilder ui, MethodInfo m, ParameterInfo p, Type pt)
		{
			ui.HorizontalLayout();
			LocaleString str = m.Name;
			var b = ui.Button(in str);
			var bpt = typeof(ButtonEventHandler<>).MakeGenericType(pt);
			Type t = genType.MakeGenericType(pt);
			var c = b.Slot.AttachComponent(t);
			Type rt = typeof(SyncDelegate<>).MakeGenericType(bpt);
			rt.GetProperty("Target").SetValue(t.GetField("ButtonPressed").GetValue(c), m.CreateDelegate(bpt, m.IsStatic ? null : worker));
			SyncMemberEditorBuilder.Build(c.GetSyncMember("Argument"), p.Name, t.GetField("Argument"), ui);
			ui.NestOut();
		}

		static void funcWithoutArgs(Worker w, UIBuilder ui, MethodDataCache data)
		{
			//ExtraDebug("Func without args");
			var b = funcButton(w, ui, data);
			var returnType = data.method.ReturnType;
			//if (returnType)
			//b.LocalPressed += (btn, data) =>
			//{
			//	m.Invoke(w, null);
			//};
		}

		static void funcWithArgs(Worker w, UIBuilder ui, ParameterInfo[] param, MethodDataCache data)
		{
			//ExtraDebug("Func with args");
			var b = funcButton(w, ui, data, param);
			//b.LocalPressed += (btn, data) =>
			//{
			//	m.Invoke(w, null);
			//};
		}

		static Button funcButton(Worker w, UIBuilder ui, MethodDataCache data, ParameterInfo[] param = null)
		{
			var c = data.isFuncSupported ? RadiantUI_Constants.MidLight.ORANGE : RadiantUI_Constants.MidLight.RED;
			//var c = RadiantUI_Constants.Sub.ORANGE;
			var invalidText = data.isFuncSupported ? "" : "UNSUPPORTED: ";
			return ui.Button($"{invalidText}{data.method.ReturnType.GetNiceName()} {data.method.Name}({GetParamString(param)})", c);
		}
	}
}